// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARCRkvcU28tHQs4SNS2sU_8g5eOWw1AME',
    appId: '1:94472569484:ios:d4d911f6d977363cb7f1a9',
    messagingSenderId: '94472569484',
    projectId: 'social-media-app-a9203',
    storageBucket: 'social-media-app-a9203.firebasestorage.app',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhvkZJeoXvg79auNKB1xllDbQT4DXm55Y',
    appId: '1:94472569484:web:8811f795329d0f99b7f1a9',
    messagingSenderId: '94472569484',
    projectId: 'social-media-app-a9203',
    authDomain: 'social-media-app-a9203.firebaseapp.com',
    storageBucket: 'social-media-app-a9203.firebasestorage.app',
    measurementId: 'G-S581KW796Q',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhvkZJeoXvg79auNKB1xllDbQT4DXm55Y',
    appId: '1:94472569484:web:8811f795329d0f99b7f1a9',
    messagingSenderId: '94472569484',
    projectId: 'social-media-app-a9203',
    authDomain: 'social-media-app-a9203.firebaseapp.com',
    storageBucket: 'social-media-app-a9203.firebasestorage.app',
    measurementId: 'G-S581KW796Q',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARCRkvcU28tHQs4SNS2sU_8g5eOWw1AME',
    appId: '1:94472569484:ios:d4d911f6d977363cb7f1a9',
    messagingSenderId: '94472569484',
    projectId: 'social-media-app-a9203',
    storageBucket: 'social-media-app-a9203.firebasestorage.app',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgCICObEfoBftH1UFTq2coEmuvzWWbIO0',
    appId: '1:94472569484:android:e1e77974cbd6fbbab7f1a9',
    messagingSenderId: '94472569484',
    projectId: 'social-media-app-a9203',
    storageBucket: 'social-media-app-a9203.firebasestorage.app',
  );
}
